name: Building Docker images

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[main skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./${{ matrix.os }}/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/:asciinema_playground
          cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/:asciinema_playground
          build-args: BUILDKIT_INLINE_CACHE=1
